# Generated by Django 4.0.6 on 2024-07-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0035_escalavocales_palabraspacientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informe',
            new_name='Protocolo',
        ),
        migrations.RenameModel(
            old_name='TpInforme',
            new_name='TpProtocolo',
        ),
        migrations.AlterModelOptions(
            name='protocolo',
            options={'verbose_name_plural': 'protocolos'},
        ),
        migrations.AlterModelOptions(
            name='tpprotocolo',
            options={'verbose_name_plural': 'tipo protocolos'},
        ),
        migrations.RenameField(
            model_name='protocolo',
            old_name='id_informe',
            new_name='id_protocolo',
        ),
        migrations.RenameField(
            model_name='protocolo',
            old_name='tp_informe',
            new_name='tp_protocolo',
        ),
        migrations.RenameField(
            model_name='tpprotocolo',
            old_name='tipo_informe',
            new_name='tipo_protocolo',
        ),
        migrations.RenameField(
            model_name='tpprotocolo',
            old_name='tp_informe_id',
            new_name='tp_protocolo_id',
        ),
        migrations.RemoveField(
            model_name='esv',
            name='id_informe',
        ),
        migrations.RemoveField(
            model_name='grbas',
            name='id_informe',
        ),
        migrations.RemoveField(
            model_name='pautaterapeutica',
            name='fk_informe',
        ),
        migrations.RemoveField(
            model_name='rasati',
            name='id_informe',
        ),
        migrations.AddField(
            model_name='esv',
            name='id_protocolo',
            field=models.OneToOneField(db_column='id_protocolo', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.protocolo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grbas',
            name='id_protocolo',
            field=models.OneToOneField(db_column='id_protocolo', default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.protocolo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pautaterapeutica',
            name='fk_protocolo',
            field=models.ForeignKey(db_column='fk_protocolo', default=1, on_delete=django.db.models.deletion.CASCADE, to='rtdf.protocolo'),
        ),
        migrations.AddField(
            model_name='rasati',
            name='id_protocolo',
            field=models.OneToOneField(db_column='id_protocolo', default=2, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rtdf.protocolo'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='protocolo',
            table='protocolo',
        ),
        migrations.AlterModelTable(
            name='tpprotocolo',
            table='tp_protocolo',
        ),
    ]
