# Generated by Django 4.0.6 on 2024-07-18 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0036_rename_informe_protocolo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'géneros',
                'db_table': 'genero',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_genero',
            field=models.ForeignKey(db_column='id_genero', null=True, on_delete=django.db.models.deletion.PROTECT, to='rtdf.genero'),
        ),
    ]
