# Generated by Django 4.0.6 on 2024-07-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0037_genero_usuario_id_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioIndepe',
            fields=[
                ('id_audio', models.AutoField(primary_key=True, serialize=False)),
                ('url_audio', models.CharField(max_length=200)),
                ('fecha_audio', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'audios independientes',
                'db_table': 'audio_independiente',
            },
        ),
        migrations.CreateModel(
            name='TipoACV',
            fields=[
                ('id_acv', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_acv', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'tipo accidente cerebrovascular',
                'db_table': 'tipo_acv',
            },
        ),
        migrations.CreateModel(
            name='TipoParkinson',
            fields=[
                ('id_parkinson', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_parkinson', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'tipo parkinson',
                'db_table': 'tipo_parkinson',
            },
        ),
        migrations.CreateModel(
            name='TpDiagnosticoFono',
            fields=[
                ('id_tp_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('tp_diagnostico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'tipo diagnostico fono',
                'db_table': 'tipo_diagnostico_fono',
            },
        ),
        migrations.AlterField(
            model_name='tipodiabetes',
            name='tipo_diabetes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipohipertension',
            name='tipo_hipertension',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='FormularioAudio',
            fields=[
                ('id_form_audio', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=30)),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('ap_paterno', models.CharField(max_length=30)),
                ('ap_materno', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('timestamp', models.DateField()),
                ('fk_profesional_salud', models.ForeignKey(db_column='fk_profesional_salud', on_delete=django.db.models.deletion.CASCADE, to='rtdf.profesionalsalud')),
                ('fk_tipo_acv', models.ForeignKey(db_column='fk_tipo_acv', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tipoacv')),
                ('fk_tipo_diabetes', models.ForeignKey(db_column='fk_tipo_diabetes', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tipodiabetes')),
                ('fk_tipo_hipertension', models.ForeignKey(db_column='fk_tipo_hipertension', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tipohipertension')),
                ('fk_tipo_parkinson', models.ForeignKey(db_column='fk_tipo_parkinson', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tipoparkinson')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.PROTECT, to='rtdf.genero')),
                ('id_tp_diagnostico', models.ForeignKey(db_column='id_tp_diagnostico', on_delete=django.db.models.deletion.PROTECT, to='rtdf.tpdiagnosticofono')),
            ],
            options={
                'verbose_name_plural': 'Formulario audios',
                'db_table': 'formulario_audio',
            },
        ),
        migrations.CreateModel(
            name='AudioscoefIndepe',
            fields=[
                ('id_audiocoeficientes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('fecha_coeficiente', models.DateTimeField()),
                ('f0', models.CharField(max_length=100)),
                ('f1', models.CharField(max_length=100)),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.CharField(max_length=100)),
                ('f4', models.CharField(max_length=100)),
                ('intensidad', models.CharField(max_length=100)),
                ('hnr', models.CharField(max_length=100)),
                ('local_jitter', models.CharField(max_length=100)),
                ('local_absolute_jitter', models.CharField(max_length=100)),
                ('rap_jitter', models.CharField(max_length=100)),
                ('ppq5_jitter', models.CharField(max_length=100)),
                ('ddp_jitter', models.CharField(max_length=100)),
                ('local_shimmer', models.CharField(max_length=100)),
                ('local_db_shimmer', models.CharField(max_length=100)),
                ('apq3_shimmer', models.CharField(max_length=100)),
                ('aqpq5_shimmer', models.CharField(max_length=100)),
                ('apq11_shimmer', models.CharField(max_length=100)),
                ('id_audio', models.ForeignKey(db_column='id_audio', on_delete=django.db.models.deletion.CASCADE, to='rtdf.audioindepe')),
            ],
            options={
                'verbose_name_plural': 'audiocoeficiente independientes',
                'db_table': 'audioscoeficientes_indepe',
            },
        ),
        migrations.AddField(
            model_name='audioindepe',
            name='id_form_audio',
            field=models.ForeignKey(db_column='id_form_audio', on_delete=django.db.models.deletion.CASCADE, to='rtdf.formularioaudio'),
        ),
    ]
