# Generated by Django 4.0.6 on 2024-07-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0038_audioindepe_tipoacv_tipoparkinson_tpdiagnosticofono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioscoefindepe',
            name='fk_tipo_llenado',
            field=models.ForeignKey(db_column='fk_tipo_llenado', null=True, on_delete=django.db.models.deletion.PROTECT, to='rtdf.tpllenado'),
        ),
    ]
