# Generated by Django 4.0.6 on 2024-08-06 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0039_audioscoefindepe_fk_tipo_llenado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSeguimiento',
            fields=[
                ('id_estado_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado_seguimiento', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'estados seguimientos',
                'db_table': 'estado_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('principio_activo', models.CharField(max_length=120)),
                ('marca', models.CharField(blank=True, max_length=45, null=True)),
                ('accion_terapeutica', models.CharField(blank=True, max_length=45, null=True)),
                ('laboratorio', models.CharField(blank=True, max_length=45, null=True)),
                ('presentacion', models.CharField(max_length=120)),
                ('total_mg', models.IntegerField()),
                ('indicacion', models.CharField(blank=True, max_length=120, null=True)),
                ('cant_caja', models.CharField(blank=True, max_length=45, null=True)),
                ('ges', models.CharField(blank=True, max_length=1, null=True)),
                ('cmax', models.CharField(blank=True, max_length=45, null=True)),
                ('vida_media', models.CharField(blank=True, max_length=120, null=True)),
                ('interacciones', models.TextField(blank=True, null=True)),
                ('dosificacion', models.TextField(blank=True, null=True)),
                ('OBS', models.TextField(blank=True, null=True)),
                ('valor_ref_oferta', models.IntegerField(blank=True, null=True)),
                ('valor_ref_normal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'medicamentos',
                'db_table': 'medicamento',
            },
        ),
        migrations.CreateModel(
            name='PacienteReceta',
            fields=[
                ('id_paciente_receta', models.AutoField(primary_key=True, serialize=False)),
                ('indicacion_ingesta', models.CharField(max_length=100)),
                ('total_dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateField()),
                ('fk_medicamento', models.ForeignKey(db_column='fk_medicamento', on_delete=django.db.models.deletion.PROTECT, to='rtdf.medicamento')),
                ('fk_relacion_pa_pro', models.ForeignKey(db_column='fk_relacion_pa_pro', on_delete=django.db.models.deletion.PROTECT, to='rtdf.relacionpapro')),
            ],
            options={
                'verbose_name_plural': 'paciente recetas',
                'db_table': 'paciente_receta',
            },
        ),
        migrations.CreateModel(
            name='PacienteSeguimiento',
            fields=[
                ('id_paciente_segui', models.AutoField(primary_key=True, serialize=False)),
                ('paciente_seguimiento', models.CharField(max_length=120)),
                ('total_ingesta', models.DecimalField(decimal_places=2, max_digits=5)),
                ('timestamp', models.DateField()),
                ('fk_estado_seguimiento', models.ForeignKey(db_column='fk_estado_seguimiento', on_delete=django.db.models.deletion.PROTECT, to='rtdf.estadoseguimiento')),
                ('fk_paciente_receta', models.ForeignKey(db_column='fk_paciente_receta', on_delete=django.db.models.deletion.PROTECT, to='rtdf.pacientereceta')),
            ],
            options={
                'verbose_name_plural': 'paciente seguimientos',
                'db_table': 'paciente_seguimiento',
            },
        ),
        migrations.CreateModel(
            name='PacienteIngesta',
            fields=[
                ('id_paciente_ingesta', models.AutoField(primary_key=True, serialize=False)),
                ('ingesta', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hora_ingesta', models.TimeField()),
                ('fk_paciente_segui', models.ForeignKey(db_column='fk_paciente_segui', on_delete=django.db.models.deletion.PROTECT, to='rtdf.pacienteseguimiento')),
            ],
            options={
                'verbose_name_plural': 'paciente ingestas',
                'db_table': 'paciente_ingesta',
            },
        ),
    ]
