# Generated by Django 4.0.6 on 2024-08-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0040_estadoseguimiento_medicamento_pacientereceta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='total_mg',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
