# Generated by Django 4.0.6 on 2024-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0042_alter_pacientereceta_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteseguimiento',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
