# Generated by Django 4.0.6 on 2024-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0043_alter_pacienteseguimiento_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteseguimiento',
            name='paciente_seguimiento',
            field=models.TextField(),
        ),
    ]
