# Generated by Django 4.0.6 on 2024-08-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0044_alter_pacienteseguimiento_paciente_seguimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteingesta',
            name='fk_paciente_segui',
            field=models.ForeignKey(db_column='fk_paciente_segui', on_delete=django.db.models.deletion.CASCADE, to='rtdf.pacienteseguimiento'),
        ),
        migrations.AlterField(
            model_name='pacienteseguimiento',
            name='fk_paciente_receta',
            field=models.ForeignKey(db_column='fk_paciente_receta', on_delete=django.db.models.deletion.CASCADE, to='rtdf.pacientereceta'),
        ),
    ]
