# Generated by Django 4.0.6 on 2024-08-13 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0045_alter_pacienteingesta_fk_paciente_segui_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteAudioIngesta',
            fields=[
                ('id_audio_ingesta', models.AutoField(primary_key=True, serialize=False)),
                ('url_audio', models.CharField(max_length=200)),
                ('fecha_audio', models.DateTimeField()),
                ('fk_paciente_ingesta', models.ForeignKey(db_column='fk_paciente_ingesta', on_delete=django.db.models.deletion.CASCADE, to='rtdf.pacienteingesta')),
            ],
            options={
                'verbose_name_plural': 'audios paciente ingesta',
                'db_table': 'paciente_audio_ingesta',
            },
        ),
    ]
