# Generated by Django 4.0.6 on 2024-08-13 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0046_pacienteaudioingesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteaudioingesta',
            name='fecha_audio',
        ),
        migrations.AddField(
            model_name='pacienteaudioingesta',
            name='hora_audio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pacienteingesta',
            name='hora_ingesta',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
