# Generated by Django 4.0.6 on 2024-08-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0047_remove_pacienteaudioingesta_fecha_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacienteaudioingesta',
            name='hora_audio',
            field=models.DateTimeField(),
        ),
    ]
