# Generated by Django 4.0.6 on 2024-08-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0048_alter_pacienteaudioingesta_hora_audio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteAudioIngesta',
        ),
    ]
