# Generated by Django 4.0.6 on 2024-08-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0049_delete_pacienteaudioingesta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacienteingesta',
            old_name='hora_ingesta',
            new_name='fecha_ingesta',
        ),
    ]
