# Generated by Django 4.0.6 on 2024-08-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0050_rename_hora_ingesta_pacienteingesta_fecha_ingesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacienteingesta',
            name='fecha_ingesta',
        ),
        migrations.AddField(
            model_name='pacienteingesta',
            name='hora_ingesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
