# Generated by Django 4.0.6 on 2024-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtdf', '0052_pacienteingesta_recordatorio_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientereceta',
            name='estado',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
